AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Jersey API - com.neu.aws.distributed::hw1
Outputs:
  Hw1Api:
    Description: URL for application
    Export:
      Name: Hw1Api
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
Resources:
  Hw1Function:
    Properties:
      CodeUri: s3://distributedsystem/62d3ee2e61646d3c21ece89cb9694db3
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: com.neu.aws.distributed.StreamLambdaHandler::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
