AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - com.neu.aws.distributed::hw1
Resources:
  Hw1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.neu.aws.distributed.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/hw1-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Hw1Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Hw1Api
